name: Publish IPFS
on:
  push:

env:
  WEB3Token: ${{ secrets.WEB3APITOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
      # Checks-out your repository under $GITHUB_WORKSPACE, 
      # so your workflow can access it
    - name: Checkout repo
      uses: actions/checkout@master
      
    - run: |
        npm i --global ipfs-car
        ipfs-car --pack $GITHUB_WORKSPACE --verbose --output /tmp/output.car
        ls -la $GITHUB_WORKSPACE
        ls -la /tmp/output.car
        IPFS=$(ipfs-car --hash /tmp/output.car)
        echo $IPFS 
        curl -X POST \
          'https://api.web3.storage/car' \
          -H 'accept: application/json' \
          -H "Authorization: Bearer $WEB3Token" \
          -H 'Content-Type: application/vnd.ipld.car' \
          --data-binary '@/tmp/output.car'
  
